export default [
  {
    id: 1,
    title: "Pulp Fiction",
    category: "Crime",
    genre: "Drama",
    director: "Quentin Tarantino",
    year: 1994,
    imageURL: "/img/jungle-cruise.jpeg",
    rating: 8.9,
    description:
      "The lives of two hitmen, a boxer, a gangster's wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
  },
  {
    id: 2,
    title: "The Transporter",
    category: "Action",
    genre: "Thriller",
    director: "Louis Leterrier, Corey Yuen",
    year: 2002,
    imageURL: "https://m.media-amazon.com/images/I/91g5n5Dy-3L._AC_SY679_.jpg",
    rating: 6.8,
    description:
      "Frank Martin, a skilled driver and mercenary, gets entangled in a dangerous mission when he breaks his own rule: never open the package.",
  },
  {
    id: 3,
    title: "The Godfather",
    category: "Crime",
    genre: "Drama",
    director: "Francis Ford Coppola",
    year: 1972,
    imageURL: "https://m.media-amazon.com/images/I/91PjZemwBfL._AC_SY679_.jpg",
    rating: 9.2,
    description:
      "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
  },
  {
    id: 4,
    title: "Inception",
    category: "Sci-Fi",
    genre: "Thriller",
    director: "Christopher Nolan",
    year: 2010,
    imageURL: "https://m.media-amazon.com/images/I/91G7Z0JzwWL._AC_SY679_.jpg",
    rating: 8.8,
    description:
      "A thief who enters people's dreams to steal secrets must plant an idea in a target’s subconscious, but his past haunts him.",
  },
  {
    id: 5,
    title: "The Dark Knight",
    category: "Action",
    genre: "Superhero",
    director: "Christopher Nolan",
    year: 2008,
    imageURL: "https://m.media-amazon.com/images/I/51k0qaap1cL._AC_.jpg",
    rating: 9.0,
    description:
      "Batman faces the Joker, a criminal mastermind who seeks to create chaos in Gotham City and push the hero to his limits.",
  },
  {
    id: 6,
    title: "Gladiator",
    category: "Historical",
    genre: "Action",
    director: "Ridley Scott",
    year: 2000,
    imageURL: "https://m.media-amazon.com/images/I/71fdlV9FF5L._AC_SY679_.jpg",
    rating: 8.5,
    description:
      "A betrayed Roman general seeks revenge against the corrupt emperor who murdered his family and sent him into slavery.",
  },
  {
    id: 7,
    title: "Fight Club",
    category: "Drama",
    genre: "Thriller",
    director: "David Fincher",
    year: 1999,
    imageURL: "https://m.media-amazon.com/images/I/81D+KJkO2PL._AC_SY679_.jpg",
    rating: 8.8,
    description:
      "An insomniac office worker and a devil-may-care soap maker form an underground fight club that spirals out of control.",
  },
  {
    id: 8,
    title: "Interstellar",
    category: "Sci-Fi",
    genre: "Adventure",
    director: "Christopher Nolan",
    year: 2014,
    imageURL: "https://m.media-amazon.com/images/I/91kFYg4fX3L._AC_SY679_.jpg",
    rating: 8.7,
    description:
      "A team of explorers travels through a wormhole in space to ensure humanity's survival, facing time and space paradoxes.",
  },
  {
    id: 9,
    title: "The Matrix",
    category: "Sci-Fi",
    genre: "Action",
    director: "Lana Wachowski, Lilly Wachowski",
    year: 1999,
    imageURL: "https://m.media-amazon.com/images/I/51EG732BV3L._AC_.jpg",
    rating: 8.7,
    description:
      "A hacker learns that reality is a simulated world controlled by intelligent machines and joins a rebellion to fight for freedom.",
  },
  {
    id: 10,
    title: "The Shawshank Redemption",
    category: "Drama",
    genre: "Crime",
    director: "Frank Darabont",
    year: 1994,
    imageURL: "https://m.media-amazon.com/images/I/51zUbui+gbL._AC_.jpg",
    rating: 9.3,
    description:
      "Two imprisoned men bond over several years, finding solace and redemption through acts of common decency.",
  },
];
